version: '3.8'

services:
  hexward-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./hexward.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./static:/app/static
      - ./hexward.db:/app/hexward.db
    devices:
      - /dev/video0:/dev/video0  # For camera access
    restart: unless-stopped

  hexward-frontend:
    build: ../
    ports:
      - "5173:5173"
    depends_on:
      - hexward-backend
    restart: unless-stopped