// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vibrblviwllnmehgyupy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpYnJibHZpd2xsbm1laGd5dXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDU5MTcsImV4cCI6MjA2ODY4MTkxN30.298z5Kpo_U2DXuIbOW2vZmoFnrejxOgQdBVXHGQa2X4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});